package org.symlabs.browser.config;

import javax.swing.DefaultListModel;
import org.apache.log4j.Logger;
import org.symlabs.browser.editor.EditorFieldValue;
import org.symlabs.browser.editor.EditorTable;
import org.symlabs.store.BrowserPreferences;
import org.symlabs.store.SaveAndLoadBrowserPreferences;
import org.symlabs.util.Utils;

/**
 * <p>Titulo: PreferencesWin </p>
 * <p>Descripcion: Class that manages the configuration window. </p>
 * <p>Copyright: Emilio Fernandez  2009</p>
 * @author Emilio J. Fernandez Rey
 * @version 1.0
 * @id $Id: PreferencesWin.java,v 1.2 2009-08-07 10:23:54 efernandez Exp $
 */
public class PreferencesWin extends javax.swing.JFrame {
    
    /**Attribute used to display the debug message*/
    private static Logger logger = Logger.getLogger(PreferencesWin.class);

    /** Creates new form ConfigurationWin */
    public PreferencesWin() {
        initComponents();
        initProperties();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        editorButtonGroup = new javax.swing.ButtonGroup();
        lookAndFeelPanel = new javax.swing.JPanel();
        lookAndFeelLabel = new javax.swing.JLabel();
        lookAndFeelScrollPane = new javax.swing.JScrollPane();
        lookAndFeelList = new javax.swing.JList();
        changeEditorPanel = new javax.swing.JPanel();
        tableEditorRadioButton = new javax.swing.JRadioButton();
        fieldValueEditorRadioButton = new javax.swing.JRadioButton();
        commandPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuration");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lookAndFeelPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Look & Feel"));
        lookAndFeelPanel.setLayout(new java.awt.GridBagLayout());

        lookAndFeelLabel.setText("Available Look And Feel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        lookAndFeelPanel.add(lookAndFeelLabel, gridBagConstraints);

        lookAndFeelList.setBorder(null);
        lookAndFeelList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lookAndFeelList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lookAndFeelScrollPane.setViewportView(lookAndFeelList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        lookAndFeelPanel.add(lookAndFeelScrollPane, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        getContentPane().add(lookAndFeelPanel, gridBagConstraints);

        changeEditorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Default Editor"));
        changeEditorPanel.setLayout(new java.awt.GridBagLayout());

        editorButtonGroup.add(tableEditorRadioButton);
        tableEditorRadioButton.setText("Table");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        changeEditorPanel.add(tableEditorRadioButton, gridBagConstraints);

        editorButtonGroup.add(fieldValueEditorRadioButton);
        fieldValueEditorRadioButton.setText("Field-Value");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        changeEditorPanel.add(fieldValueEditorRadioButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        getContentPane().add(changeEditorPanel, gridBagConstraints);

        commandPanel.setLayout(new java.awt.GridBagLayout());

        saveButton.setText("Save changes");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        commandPanel.add(saveButton, gridBagConstraints);

        cancelButton.setText("Cancel");
        cancelButton.setToolTipText("Close this windo without saving");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        commandPanel.add(cancelButton, gridBagConstraints);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        commandPanel.add(jPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        getContentPane().add(commandPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String selected = (String) this.lookAndFeelList.getSelectedValue();
        String classNameLookAndFeel= Utils.getMainWindow().getClassNameOfLookAndFeelName(selected);
        Utils.getMainWindow().setDefaultLookAndFeel(classNameLookAndFeel);

        String editor= null;
        if (this.tableEditorRadioButton.isSelected()) {
            editor =EditorTable.DEFAULT_EDITOR_TITLE;
        } else if (this.fieldValueEditorRadioButton.isSelected()) {
            editor =EditorFieldValue.DEFAULT_EDITOR_TITLE;
        }
        Utils.getMainWindow().setDefaultTypeEditor(editor);
        
        //We save the preferences
        SaveAndLoadBrowserPreferences.saveFilePreferences(new BrowserPreferences(editor,classNameLookAndFeel));
        
        this.cancelButton.setText("Close");
        this.cancelButton.setToolTipText("Close this window");
        
        this.validate();
        this.repaint();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
}//GEN-LAST:event_cancelButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel changeEditorPanel;
    private javax.swing.JPanel commandPanel;
    private javax.swing.ButtonGroup editorButtonGroup;
    private javax.swing.JRadioButton fieldValueEditorRadioButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lookAndFeelLabel;
    private javax.swing.JList lookAndFeelList;
    private javax.swing.JPanel lookAndFeelPanel;
    private javax.swing.JScrollPane lookAndFeelScrollPane;
    private javax.swing.JButton saveButton;
    private javax.swing.JRadioButton tableEditorRadioButton;
    // End of variables declaration//GEN-END:variables
    private void initProperties() {
        this.setSize(500, 300);

        //Default LookAndFeel
        String defaultLookAndFeel = Utils.getMainWindow().getDefaultLookAndFeel();
        String[][] list= Utils.getMainWindow().listAvailableLookAndFeel;
        DefaultListModel listModel = new DefaultListModel();
        for(int i=0;i<list.length;i++){
            listModel.addElement(list[i][0]);
        }
        
        this.lookAndFeelList.setModel(listModel);
        this.lookAndFeelList.setSelectedIndex(Utils.getMainWindow().getIndexOfLookAndFeelClassName(defaultLookAndFeel));


        //Default Editor
        String defaultEditor = Utils.getMainWindow().getDefaultTypeEditor();
        if (defaultEditor.equals(EditorTable.DEFAULT_EDITOR_TITLE)) {
            this.tableEditorRadioButton.setSelected(true);
        } else if (defaultEditor.equals(EditorFieldValue.DEFAULT_EDITOR_TITLE)) {
            this.fieldValueEditorRadioButton.setSelected(true);
        }
    }
}
