package org.symlabs.browser.help;

import org.symlabs.util.Utils;

/**
 * <p>Titulo: AboutWin </p>
 * <p>Descripcion: Class that shows the information of the window</p>
 * <p>Copyright: Emilio Fernandez  2009</p>
 * @author Emilio J. Fernandez Rey
 * @version 1.0
 * @id $Id: AboutWin.java,v 1.2 2009-08-27 10:53:38 efernandez Exp $
 */
public class AboutWin extends javax.swing.JFrame {
    
    /**Attribute that contains the title of the browser*/
    private static final String FRAME_TITLE="About "+Utils.BROWSER_TITLE;
    /**Attribute that contains the title shown in the window*/
    private static final String BROWSER_TITLE=Utils.BROWSER_TITLE;
    /**Attribute that contains the description of the browser*/
    private static final String BROWSER_DESCRIPTION=
            "<HTML>"+
            "<br>" +  
            "The most usefull application to browse your Server LDAP"+
            "<br>" +  
            ""+
            "</HTML>";
    /**Attribute that contains the product version of the browser*/
    private static final String BROWSER_PRODUCT_VERSION = 
            "<HTML>"+
            "Product Version: "+ Utils.BROWSER_TITLE+" "+ Utils.BROWSER_VERSION+
            "</HTML>";
    /**Attribute that contains the author of the browser*/
    private static final String BROWSER_AUTHOR=Utils.BROWSER_TITLE+" developed by Emilio J Fernandez Rey";
    /**Attribute that contains the acknowledgements of the browser*/
    private static final String BROWSER_ACKNOWLEDGEMENTS="Acknowledgements: Symlabs S.A.";
    /**Attribute that contains the copyright of the browser*/
    private static final String BROWSER_COPYRIGHT="Copyright @ 2009";
            
    
    /** Creates new form AboutWin */
    public AboutWin() {
        initComponents();
        this.setSize(500,300);
        this.setLocationRelativeTo(Utils.getMainWindow());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        textPanel = new javax.swing.JPanel();
        descriptionLabel = new javax.swing.JLabel();
        productVersionLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        copyrightLabel = new javax.swing.JLabel();
        acknowledgementsLabel = new javax.swing.JLabel();
        commandPanel = new javax.swing.JPanel();
        emptyPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(AboutWin.FRAME_TITLE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        titlePanel.setLayout(new java.awt.GridBagLayout());

        titleLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 24));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText(AboutWin.BROWSER_TITLE);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 4, 6, 4);
        titlePanel.add(titleLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 4, 12, 4);
        getContentPane().add(titlePanel, gridBagConstraints);

        textPanel.setLayout(new java.awt.GridBagLayout());

        descriptionLabel.setText(AboutWin.BROWSER_DESCRIPTION);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 4, 2);
        textPanel.add(descriptionLabel, gridBagConstraints);

        productVersionLabel.setText(AboutWin.BROWSER_PRODUCT_VERSION);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 4, 2);
        textPanel.add(productVersionLabel, gridBagConstraints);

        authorLabel.setText(AboutWin.BROWSER_AUTHOR);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 4, 2);
        textPanel.add(authorLabel, gridBagConstraints);

        copyrightLabel.setText(AboutWin.BROWSER_COPYRIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 4, 2);
        textPanel.add(copyrightLabel, gridBagConstraints);

        acknowledgementsLabel.setText(AboutWin.BROWSER_ACKNOWLEDGEMENTS);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 4, 2);
        textPanel.add(acknowledgementsLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        getContentPane().add(textPanel, gridBagConstraints);

        commandPanel.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout emptyPanelLayout = new javax.swing.GroupLayout(emptyPanel);
        emptyPanel.setLayout(emptyPanelLayout);
        emptyPanelLayout.setHorizontalGroup(
            emptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        emptyPanelLayout.setVerticalGroup(
            emptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        commandPanel.add(emptyPanel, gridBagConstraints);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        commandPanel.add(closeButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        getContentPane().add(commandPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acknowledgementsLabel;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel commandPanel;
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JPanel emptyPanel;
    private javax.swing.JLabel productVersionLabel;
    private javax.swing.JPanel textPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
    
}
